use super::DiagnosticExplanation;

pub(super) static ENTRIES: &[DiagnosticExplanation] = &[
    DiagnosticExplanation::new(
        "MANIFEST_NOT_FOUND",
        "Project manifest missing",
        "The repository root does not contain package.json.",
        &["Run from a JavaScript project root or pass the intended --cwd."],
    ),
    DiagnosticExplanation::new(
        "MANIFEST_INVALID",
        "Project manifest invalid",
        "package.json could not be parsed as a JSON object.",
        &["Repair package.json and inspect again."],
    ),
    DiagnosticExplanation::new(
        "MANIFEST_INVALID_JSON",
        "Project manifest invalid",
        "package.json contains invalid JSON.",
        &["Repair package.json syntax and inspect again."],
    ),
    DiagnosticExplanation::new(
        "PM_SOURCE_NOT_DETECTED",
        "Source package manager not detected",
        "Repository evidence is insufficient to select a source safely.",
        &["Add an explicit packageManager field or repair source evidence."],
    ),
    DiagnosticExplanation::new(
        "PM_PACKAGE_MANAGER_FIELD_UNKNOWN",
        "Package manager field unknown",
        "The packageManager field does not identify a supported adapter and version.",
        &["Use a supported package manager name with an explicit version."],
    ),
    DiagnosticExplanation::new(
        "PM_SOURCE_AMBIGUOUS",
        "Source package manager ambiguous",
        "Strong evidence points to more than one source package manager.",
        &["Remove stale lockfiles or configuration and inspect again."],
    ),
    DiagnosticExplanation::new(
        "PM_CONFLICTING_EVIDENCE",
        "Package manager evidence conflicts",
        "A source was selected while other strong package-manager evidence remains.",
        &["Review and remove stale source artifacts before apply."],
    ),
    DiagnosticExplanation::new(
        "PM_TARGET_UNSUPPORTED",
        "Target package manager unsupported",
        "The requested target does not match a registered production adapter.",
        &["Run pkgshift support and select a listed target identifier."],
    ),
    DiagnosticExplanation::new(
        "PM_TARGET_PREVIEW",
        "Target adapter is preview",
        "The target does not carry production migration guarantees.",
        &["Select a production target or wait for verified adapter coverage."],
    ),
    DiagnosticExplanation::new(
        "PM_TARGET_ALREADY_SELECTED",
        "Target already selected",
        "The detected source and requested target are the same adapter.",
        &["Select a different target or verify the existing project."],
    ),
    DiagnosticExplanation::new(
        "CAPABILITY_LOSSY",
        "Capability transformation is lossy",
        "The target can be rendered deterministically, but source semantics or centralized policy will be reduced.",
        &["Review every loss and create a new plan with --accept-lossy only after approval."],
    ),
    DiagnosticExplanation::new(
        "CAPABILITY_UNSUPPORTED",
        "Capability unsupported",
        "The target has no safe representation for an observed source capability.",
        &["Remove the capability, select another target, or add a verified adapter rule."],
    ),
    DiagnosticExplanation::new(
        "CAPABILITY_UNKNOWN",
        "Capability support unknown",
        "Authoritative evidence is insufficient to classify a source capability for the target.",
        &["Add authoritative target evidence or choose a known target."],
    ),
    DiagnosticExplanation::new(
        "LOSSY_ACCEPTANCE_REQUIRED",
        "Lossy acceptance required",
        "The plan contains reviewed transformations that cannot preserve all source semantics.",
        &["Review the decisions and create a new plan with --accept-lossy."],
    ),
    DiagnosticExplanation::new(
        "PLAN_NOT_EXECUTABLE",
        "Plan is not executable",
        "The plan is blocked, preview-only, or a no-op.",
        &["Resolve blocking diagnostics and create a production-target plan."],
    ),
    DiagnosticExplanation::new(
        "PLAN_ARTIFACT_INVALID",
        "Plan artifact invalid",
        "The stored plan lacks required execution or verification data.",
        &["Discard it and create a new plan."],
    ),
    DiagnosticExplanation::new(
        "CONFIGURATION_PARSE_FAILED",
        "Configuration parsing failed",
        "A migration-relevant configuration file could not be normalized safely.",
        &["Repair the configuration and inspect again."],
    ),
    DiagnosticExplanation::new(
        "DEPENDENCY_SECTION_INVALID",
        "Dependency section invalid",
        "A manifest dependency section is not a JSON object.",
        &["Repair the manifest dependency section before planning."],
    ),
    DiagnosticExplanation::new(
        "DEPENDENCY_SPECIFIER_INVALID",
        "Dependency specifier invalid",
        "A dependency value is not a supported string specifier.",
        &["Replace it with a supported dependency string."],
    ),
    DiagnosticExplanation::new(
        "WORKSPACE_MANIFEST_INVALID",
        "Workspace manifest invalid",
        "A workspace package manifest could not be parsed safely.",
        &["Repair the workspace manifest before planning."],
    ),
    DiagnosticExplanation::new(
        "WORKSPACE_VERSION_REQUIRED",
        "Workspace version required",
        "A workspace protocol must become semver, but its package has no version.",
        &["Add a package version or select a target that supports the protocol."],
    ),
    DiagnosticExplanation::new(
        "WORKSPACE_PATTERN_UNSUPPORTED",
        "Workspace pattern unsupported",
        "Workspace membership uses glob syntax outside the deterministic matcher.",
        &["Use literal, *, **, ?, or leading-exclusion patterns."],
    ),
    DiagnosticExplanation::new(
        "WORKSPACE_SPECIFIER_UNSUPPORTED",
        "Workspace specifier unsupported",
        "A workspace dependency uses an alias, path, or range outside safe expansion.",
        &["Use workspace:*, workspace:^, workspace:~, or simple semver."],
    ),
    DiagnosticExplanation::new(
        "CATALOG_ENTRY_NOT_FOUND",
        "Catalog entry missing",
        "A catalog dependency does not resolve through the selected source catalog.",
        &["Repair the source catalog and inspect again."],
    ),
    DiagnosticExplanation::new(
        "REGISTRY_SECRET_REQUIRES_ENVIRONMENT_REFERENCE",
        "Registry secret requires an environment reference",
        "A literal registry credential cannot enter a persisted plan.",
        &["Replace it with an environment-variable reference and re-plan."],
    ),
    DiagnosticExplanation::new(
        "NPMRC_SETTING_UNSUPPORTED",
        "npm setting unsupported",
        "The target translation cannot preserve an observed .npmrc setting deterministically.",
        &["Move the setting to an equivalent target configuration or remove it."],
    ),
    DiagnosticExplanation::new(
        "TRANSFORMATION_UNIMPLEMENTED",
        "Transformation unavailable",
        "The target capability exists, but the current adapter cannot render it deterministically.",
        &["Remove the feature, choose another target, or add a verified rule."],
    ),
    DiagnosticExplanation::new(
        "TRANSFORMATION_MANUAL_REQUIRED",
        "Manual transformation required",
        "The source policy cannot be reduced automatically without unsafe output.",
        &["Resolve the policy manually and create a new plan."],
    ),
    DiagnosticExplanation::new(
        "NATIVE_IMPORT_UNAVAILABLE",
        "Native lockfile import unavailable",
        "The target cannot safely import the observed source dependency state.",
        &["Review clean resolution behavior or select a target with a supported importer."],
    ),
    DiagnosticExplanation::new(
        "NESTED_OVERRIDE_UNSUPPORTED",
        "Nested override unsupported",
        "The source override structure exceeds the deterministic target mapping.",
        &["Flatten or simplify the override policy before planning."],
    ),
    DiagnosticExplanation::new(
        "RESOLUTION_SELECTOR_UNSUPPORTED",
        "Resolution selector unsupported",
        "A dependency resolution selector cannot be represented with target fidelity.",
        &["Simplify the selector or choose a compatible target."],
    ),
    DiagnosticExplanation::new(
        "PACKAGE_EXTENSIONS_UNSUPPORTED",
        "Package extensions unsupported",
        "Observed package-extension data falls outside the shared portable schema.",
        &["Reduce the extension to supported fields or preserve it manually."],
    ),
    DiagnosticExplanation::new(
        "PATCH_FILE_NOT_FOUND",
        "Patch file missing",
        "A declared patched dependency does not resolve to a repository patch file.",
        &["Restore the patch file or remove the declaration."],
    ),
    DiagnosticExplanation::new(
        "PATCH_FORMAT_UNSUPPORTED",
        "Patch format unsupported",
        "The patch content is outside the deterministic text patch subset.",
        &["Regenerate it as a supported unified text patch."],
    ),
    DiagnosticExplanation::new(
        "PATCH_LOCATOR_UNSUPPORTED",
        "Patch locator unsupported",
        "The package-manager patch locator cannot be normalized safely.",
        &["Use a repository-relative supported patch locator."],
    ),
    DiagnosticExplanation::new(
        "PATCH_PATH_UNSUPPORTED",
        "Patch path unsupported",
        "A patch path escapes the repository, traverses a symbolic link, or has unsupported syntax.",
        &["Move it to a regular repository-relative file."],
    ),
    DiagnosticExplanation::new(
        "PATCH_POLICY_CONFLICT",
        "Patch policy conflict",
        "Multiple source policies assign incompatible patches to one package.",
        &["Resolve the conflicting declarations before planning."],
    ),
    DiagnosticExplanation::new(
        "PATCH_POLICY_UNSUPPORTED",
        "Patch policy unsupported",
        "The target cannot express the observed patch ownership semantics.",
        &["Choose a compatible target or remove the patch policy."],
    ),
    DiagnosticExplanation::new(
        "PATCH_RESOLUTION_CONFLICT",
        "Patch resolution conflict",
        "Patch resolution evidence points to incompatible package versions or files.",
        &["Normalize the source patch resolution before planning."],
    ),
    DiagnosticExplanation::new(
        "PATCH_RESOLUTION_EVIDENCE_MISSING",
        "Patch resolution evidence missing",
        "A range or name-only patch selector cannot be bound to an exact Yarn package locator from the source project or lock graph.",
        &["Retain a source lockfile or use an exact registry version in a project dependency."],
    ),
    DiagnosticExplanation::new(
        "PATCH_SELECTOR_UNSUPPORTED",
        "Patch selector unsupported",
        "The patched dependency selector is outside deterministic conversion coverage.",
        &["Use an exact supported selector or remove the patch."],
    ),
    DiagnosticExplanation::new(
        "PATCH_SOURCE_UNSUPPORTED",
        "Patch source unsupported",
        "The patch source manager or declaration shape is not supported.",
        &["Convert it to a supported source patch form first."],
    ),
    DiagnosticExplanation::new(
        "DENO_DEPENDENCY_PROTOCOL_UNSUPPORTED",
        "Deno dependency protocol unsupported",
        "Deno dependency mode cannot preserve an observed dependency protocol safely.",
        &["Use npm or jsr-compatible specifiers before planning."],
    ),
    DiagnosticExplanation::new(
        "VLT_MODIFIER_UNSUPPORTED",
        "vlt modifier unsupported",
        "An observed vlt dependency modifier cannot be mapped safely.",
        &["Remove or simplify the modifier before migration."],
    ),
    DiagnosticExplanation::new(
        "VLT_REGISTRY_AUTH_MANUAL_REQUIRED",
        "vlt registry authentication requires review",
        "The registry authentication policy cannot be persisted safely in the target plan.",
        &["Move credentials to environment-backed configuration and re-plan."],
    ),
    DiagnosticExplanation::new(
        "YARN_BUILD_POLICY_UNSUPPORTED",
        "Yarn build policy unsupported",
        "The observed Yarn lifecycle policy cannot be represented by the target.",
        &["Use an explicit portable allow-list or change targets."],
    ),
    DiagnosticExplanation::new(
        "INTEGRATION_CACHE_UNSUPPORTED",
        "Integration cache unsupported",
        "A CI cache configuration cannot be rewritten without changing its semantics.",
        &["Update the reported integration manually, then re-plan."],
    ),
    DiagnosticExplanation::new(
        "INTEGRATION_COMMAND_AMBIGUOUS",
        "Integration command ambiguous",
        "A toolchain command appears in a context where token-safe rewriting is not provable.",
        &["Make the command explicit or update the integration manually."],
    ),
    DiagnosticExplanation::new(
        "INTEGRATION_DEVCONTAINER_COMMAND_UNSUPPORTED",
        "Dev container command unsupported",
        "A dev-container lifecycle command is outside the deterministic rewrite grammar.",
        &["Simplify the command or migrate that integration manually."],
    ),
    DiagnosticExplanation::new(
        "INTEGRATION_SETUP_ACTION_UNSUPPORTED",
        "Setup action unsupported",
        "A CI setup action does not have a verified target mapping.",
        &["Replace it with a supported setup action before planning."],
    ),
    DiagnosticExplanation::new(
        "INTEGRATION_TOOLCHAIN_TARGET_UNSUPPORTED",
        "Toolchain target unsupported",
        "A registered integration cannot represent the selected target package manager.",
        &["Remove or manually update the integration."],
    ),
    DiagnosticExplanation::new(
        "INTEGRATION_VOLTA_TARGET_UNSUPPORTED",
        "Volta target unsupported",
        "Volta cannot pin the selected target through the observed manifest policy.",
        &["Remove the incompatible Volta pin or select another target."],
    ),
    DiagnosticExplanation::new(
        "LOCK_GRAPH_ENCODING_INVALID",
        "Lock graph encoding invalid",
        "A lockfile is not valid supported text or JSON input.",
        &["Regenerate the source lockfile with its owning package manager."],
    ),
    DiagnosticExplanation::new(
        "LOCK_GRAPH_FORMAT_UNSUPPORTED",
        "Lock graph format unsupported",
        "The lockfile format or version is outside verified graph extraction coverage.",
        &["Regenerate with a supported version or choose structural-only review."],
    ),
    DiagnosticExplanation::new(
        "LOCK_GRAPH_PARSE_FAILED",
        "Lock graph parsing failed",
        "Resolved dependency evidence could not be parsed safely.",
        &["Repair or regenerate the lockfile before migration."],
    ),
    DiagnosticExplanation::new(
        "SOURCE_RUNTIME_REFERENCES_PRESERVED",
        "Source runtime references preserved",
        "Runtime-specific source references remain because package-manager migration does not rewrite application APIs.",
        &["Use the separate runtime migration surface when supported."],
    ),
    DiagnosticExplanation::new(
        "TRIAL_REPOSITORY_CHANGED",
        "Source changed during trial",
        "The source repository changed while an isolated trial was running.",
        &["Stop concurrent edits and repeat the trial from a fresh plan."],
    ),
    DiagnosticExplanation::new(
        "COMPARISON_TARGET_COUNT_INVALID",
        "Comparison target set invalid",
        "Comparison requires at least two distinct supported targets.",
        &["Provide two or more unique target identifiers."],
    ),
    DiagnosticExplanation::new(
        "COMPARISON_CANDIDATE_BLOCKED",
        "Comparison candidate blocked",
        "One target has blocking capability diagnostics and was not executed.",
        &["Review that candidate's diagnostics; other targets remain independent."],
    ),
    DiagnosticExplanation::new(
        "COMPARISON_NO_EXECUTABLE_TARGETS",
        "No comparison target executable",
        "Every selected target is blocked before isolated execution.",
        &["Resolve capability blockers or select different targets."],
    ),
    DiagnosticExplanation::new(
        "COMPARISON_REPOSITORY_CHANGED",
        "Source changed during comparison",
        "The source repository changed while isolated candidate trials were running.",
        &["Stop concurrent edits and repeat the comparison."],
    ),
];
