use super::DiagnosticExplanation;

pub(super) static ENTRIES: &[DiagnosticExplanation] = &[
    DiagnosticExplanation::new(
        "RUNTIME_TARGET_UNSUPPORTED",
        "Runtime target unsupported",
        "The requested runtime migration target has no registered deterministic recipe set.",
        &["Run the documented runtime target command or keep the current runtime."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_TRIAL_UNSUPPORTED",
        "Runtime trial unsupported",
        "The runtime surface does not execute project code in a trial sandbox.",
        &["Use --dry-run to review recipes and exact file digests."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SOURCE_NOT_DETECTED",
        "Bun runtime source not detected",
        "No supported Bun application-runtime reference was found in the inspected boundary.",
        &["Confirm --cwd or keep package-manager and runtime migration separate."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_NO_SAFE_RECIPES",
        "No safe runtime recipes",
        "Bun references were detected, but none match a fully verified deterministic recipe.",
        &["Review blocking diagnostics and wait for or add a narrowly tested recipe."],
    ),
    DiagnosticExplanation::new(
        "DENO_PERMISSION_REQUIRED",
        "Deno permission required",
        "The planned runtime behavior requires a Deno permission that was not explicitly granted.",
        &["Review the evidence and repeat --deno-permission for each accepted permission."],
    ),
    DiagnosticExplanation::new(
        "DENO_PERMISSION_UNSUPPORTED",
        "Deno permission unsupported",
        "The supplied permission name is outside the supported explicit allow-list.",
        &["Use a permission named by the plan diagnostics."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_MANIFEST_INVALID",
        "Runtime manifest invalid",
        "package.json could not be interpreted safely for runtime script or type conversion.",
        &["Repair the manifest and create a new runtime plan."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_TSCONFIG_INVALID",
        "TypeScript configuration invalid",
        "tsconfig.json could not be parsed safely for Bun type cleanup.",
        &["Repair the configuration and create a new runtime plan."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_SOURCE_FILE_TOO_LARGE",
        "Runtime source file too large",
        "A source file exceeds the bounded parser input size.",
        &["Split or exclude the file before planning."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_SOURCE_SYMLINK_UNSUPPORTED",
        "Runtime source symbolic link unsupported",
        "The source boundary contains a symbolic link that the migration refuses to follow.",
        &["Use regular repository files or migrate the linked source separately."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SERVE_UNSUPPORTED",
        "Bun.serve shape unsupported",
        "A Bun.serve call does not match a recipe with proven Deno.serve equivalence.",
        &["Refactor to a supported fetch-handler shape before planning."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_FILE_UNSUPPORTED",
        "Bun.file shape unsupported",
        "A Bun.file usage does not match a safe text or directly awaited JSON recipe.",
        &["Refactor the read into a supported awaited form."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_FILE_JSON_UNSUPPORTED",
        "Bun.file JSON read unsupported",
        "JSON parsing behavior cannot be preserved by the current recipe.",
        &["Use a directly awaited JSON read or migrate the code manually."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_TEST_IMPORT_UNSUPPORTED",
        "Bun test import unsupported",
        "A bun:test import cannot be mapped to the verified node:test and assertion subset.",
        &["Reduce the import to supported test APIs before planning."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_TEST_API_UNSUPPORTED",
        "Bun test API unsupported",
        "The test source uses Bun-specific behavior without a verified target equivalent.",
        &["Replace the API or retain the current runtime for that test."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SQLITE_IMPORT_UNSUPPORTED",
        "Bun SQLite import unsupported",
        "A bun:sqlite import is outside the deterministic named Database recipe.",
        &["Use one named Database import with an optional local alias before planning."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SQLITE_API_UNSUPPORTED",
        "Bun SQLite API unsupported",
        "The source uses a bun:sqlite export or Database member outside the verified node:sqlite subset.",
        &[
            "Limit the code to the shared Database constructor, prepare, exec, and close subset or migrate it explicitly.",
        ],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SHELL_IMPORT_UNSUPPORTED",
        "Bun shell import unsupported",
        "A Bun runtime import cannot be parsed as one deterministic named dollar-sign shell template.",
        &["Use one named $ import with an optional local alias before planning."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SHELL_API_UNSUPPORTED",
        "Bun shell API unsupported",
        "The Bun import contains exports beyond the verified dollar-sign to dax recipe.",
        &["Split the $ import and migrate other Bun exports explicitly."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SCRIPT_UNSUPPORTED",
        "Bun script unsupported",
        "A package script uses Bun runtime flags or syntax outside deterministic command rewriting.",
        &["Simplify the script to a supported command form."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUNFIG_UNSUPPORTED",
        "bunfig configuration unsupported",
        "The observed bunfig.toml contains runtime semantics not represented by Deno configuration.",
        &["Resolve the reported settings manually before migration."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_GLOBAL_UNSUPPORTED",
        "Bun global unsupported",
        "A Bun global API has no registered deterministic recipe.",
        &["Replace the reported API with a portable standard before planning."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_MACRO_UNSUPPORTED",
        "Bun macro unsupported",
        "Bun macro semantics cannot be reproduced by the current Deno migration surface.",
        &["Remove the macro or keep the Bun runtime."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_MODULE_UNSUPPORTED",
        "Bun module unsupported",
        "A bun: module import has no verified Deno equivalent.",
        &["Replace the module with a portable dependency before planning."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_SHELL_UNSUPPORTED",
        "Bun shell unsupported",
        "Bun shell execution cannot be translated without changing execution semantics.",
        &["Replace it with an explicit portable process API."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_HTML_REWRITER_UNSUPPORTED",
        "HTMLRewriter unsupported",
        "Bun HTMLRewriter behavior has no registered Deno migration recipe.",
        &["Replace it with a portable implementation or retain Bun."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_AFTER_DIGEST_FAILED",
        "Runtime mutation digest mismatch",
        "A written file does not match the reviewed afterDigest.",
        &["Stop and use runtime rollback with the exact run identifier."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_BUN_RESIDUE_REMAINS",
        "Bun runtime residue remains",
        "Post-apply inspection still finds Bun application-runtime references in the supported boundary.",
        &["Inspect the verification evidence and roll back or add recipe coverage."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_EXECUTION_FAILED",
        "Runtime migration execution failed",
        "An approved runtime file mutation could not be completed safely.",
        &["Preserve the run artifact and execute its exact rollback action."],
    ),
    DiagnosticExplanation::new(
        "RUNTIME_ROLLBACK_FAILED",
        "Runtime rollback failed",
        "The runtime recovery snapshot could not restore and verify the original files.",
        &["Preserve state and inspect snapshot integrity before retrying."],
    ),
];
