[package]
name = "pkgshift-cli"
description = "Transactional package manager migration CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pkgshift"
path = "src/main.rs"

[dependencies]
clap.workspace = true
pkgshift-core = { path = "../pkgshift-core" }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
